# kustomization.yaml

resources:
  - ../../base

namespace: dev
namePrefix: dev-

commonLabels:
  app: order

patchesStrategicMerge:
  - orderpatch.yaml  # Include any patches specific to the dev environment
