<<<<<<< HEAD
# overlays/dev/kustomization.yaml

=======
>>>>>>> 7502231 (Committing local changes)
resources:
  - ../../base

namespace: dev
namePrefix: dev-

<<<<<<< HEAD
commonLabels:
  app: order

patchesStrategicMerge:
  - orderpatch.yaml  # Include any patches specific to dev environment

# Add additional resources specific to dev environment if needed
# - dev-specific-deployment.yaml
# - dev-specific-service.yaml
# ...
=======
replicas:
- name: order
  count: 5

images:
- name: shivakrishna99/orderapp:dev_25
  newName: shivakrishna99/orderapp:dev_72
>>>>>>> 7502231 (Committing local changes)
