---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: orderk8s-hpa
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    kind: Deployment
    name: orderdeploy
  targetCPUUtilizationPercentage: 60