# overlays/prod/kustomization.yaml

resources:
  - ../../base

namespace: qa
namePrefix: qa-

commonLabels:
  app: order

patchesStrategicMerge:
  - orderpatch.yaml  # Include any patches specific to prod environment

# Add additional resources specific to prod environment if needed
# - prod-specific-deployment.yaml
# - prod-specific-service.yaml
# ...
